// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/proto/paymentconfig.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentConfigService_GetPaymentGatewayConfig_FullMethodName = "/paymentconfig.PaymentConfigService/GetPaymentGatewayConfig"
)

// PaymentConfigServiceClient is the client API for PaymentConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentConfigServiceClient interface {
	GetPaymentGatewayConfig(ctx context.Context, in *PaymentMethodRequest, opts ...grpc.CallOption) (*PaymentGatewayResponse, error)
}

type paymentConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentConfigServiceClient(cc grpc.ClientConnInterface) PaymentConfigServiceClient {
	return &paymentConfigServiceClient{cc}
}

func (c *paymentConfigServiceClient) GetPaymentGatewayConfig(ctx context.Context, in *PaymentMethodRequest, opts ...grpc.CallOption) (*PaymentGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentGatewayResponse)
	err := c.cc.Invoke(ctx, PaymentConfigService_GetPaymentGatewayConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentConfigServiceServer is the server API for PaymentConfigService service.
// All implementations must embed UnimplementedPaymentConfigServiceServer
// for forward compatibility.
type PaymentConfigServiceServer interface {
	GetPaymentGatewayConfig(context.Context, *PaymentMethodRequest) (*PaymentGatewayResponse, error)
	mustEmbedUnimplementedPaymentConfigServiceServer()
}

// UnimplementedPaymentConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentConfigServiceServer struct{}

func (UnimplementedPaymentConfigServiceServer) GetPaymentGatewayConfig(context.Context, *PaymentMethodRequest) (*PaymentGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentGatewayConfig not implemented")
}
func (UnimplementedPaymentConfigServiceServer) mustEmbedUnimplementedPaymentConfigServiceServer() {}
func (UnimplementedPaymentConfigServiceServer) testEmbeddedByValue()                              {}

// UnsafePaymentConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentConfigServiceServer will
// result in compilation errors.
type UnsafePaymentConfigServiceServer interface {
	mustEmbedUnimplementedPaymentConfigServiceServer()
}

func RegisterPaymentConfigServiceServer(s grpc.ServiceRegistrar, srv PaymentConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentConfigService_ServiceDesc, srv)
}

func _PaymentConfigService_GetPaymentGatewayConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentConfigServiceServer).GetPaymentGatewayConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentConfigService_GetPaymentGatewayConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentConfigServiceServer).GetPaymentGatewayConfig(ctx, req.(*PaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentConfigService_ServiceDesc is the grpc.ServiceDesc for PaymentConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentconfig.PaymentConfigService",
	HandlerType: (*PaymentConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentGatewayConfig",
			Handler:    _PaymentConfigService_GetPaymentGatewayConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/paymentconfig.proto",
}
